### ISSUE TITLE
Add nightly Lifecycle scan

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/the-cla#107]
I recently pushed a PR to a README.md file, and the PR failed due to a new vulnerability from IQ.
This exposes a need for a nightly Lifecycle scan to detect new vulnerabilities in the project so we can be notified outside of PR's, etc. when such vulnerabilities are detectable.

**Comment by madpah** [comment]
We have Continuous Monitoring enabled in Lifecycle - so we don't need to have a workflow that does this @bhamail.

Note: We haven't set up notifications yet from Lifecycle...

**Comment by madpah** [comment]
Notifications set up @bhamail.
