### ISSUE TITLE
Add link to "how to sign commits" in message about missing commit signatures

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/the-cla#119]
This could get messy, as it starts to depend on links/pages in other projects, so maybe needs to be configurable....but maybe we should update the message about unsigned commits to include a link to here:

[Coding Conventions](https://github.com/sonatype-nexus-community/community-handbook.sonatype.com/blob/main/CONTRIBUTING.md#coding-conventions)

or

[Contribution Requirements](https://contribute.sonatype.com/docs/contributing/submitting/#contribution-requirements)

**Comment by madpah** [comment]
Fixed via #120
