### ISSUE TITLE
Allow for members of the org to be excluded from CLA checks

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/the-cla#53]
I believe the `dr-cla` did this, more or less, if someone has a @sonatype.com address, we don't need to check them, and I think further still, if we've added them as a contributor to the repo (org), etc... we should let them skate past.

Doing this by email address can be kinda goofy (because the GH API sometimes returns the no reply emails, like for yours truly), so it might need to be if they are a member of the org. I'm dropping that as a note in here because duh, you could run into that.

If we do allow for email addresses to be excluded from checks, this should be configurable, because we'd want this to work for people who aren't sonatype!

**Comment by bhamail** [comment]
Digging into this, using the user email address domain may be a problem because the `email` field is not populated by the call to get commits for the PR (only Login is reliably populated).
