### ISSUE TITLE
Update internal nightly Jenkins build to work with newest golang and node

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/the-cla#79]
The internal nightly Jenkins build is currently broken: https://jenkins.ci.sonatype.dev/job/devex/job/Free%20Tools/job/the-cla/job/the-cla-nightly/

Latest golang docker image is Alpine based, and the old node setup stuff only worked on debian distro. Gotta update node setup to be happy on Apline too.

Nightly build (and associated scans) are disabled for now.

**Comment by madpah** [comment]
We're using GitHub Actions now!
